### ISSUE TITLE
Can this library handle more than one ICU20201 at a time?

### ISSUE THREAD

**Issue by vmanoj1996** [tdk-invn-oss/ultrasonic.arduino.ICUX0201#2]

**Comment by rbuisson-invn** [comment]
Hello vmanoj1996,

Next version of this library will support 2 sensors.
This release is currently in validation stage, so it should be made public very soon.

Regards,

**Comment by rbuisson-invn** [comment]
Version 1.0.2 of this library supports up to 2 sensors.
