### ISSUE TITLE
Is INT2 exposed on TOF EVK board?

### ISSUE THREAD

**Issue by vmanoj1996** [tdk-invn-oss/ultrasonic.arduino.ICUX0201#3]
Hi, 
I want to know if INT2 from the sensor is exposed on the EVK board. Either in J5 or J10.

**Comment by rbuisson-invn** [comment]
Hi manoj1996,

INT2 is available on connector J5.6, labeled PB2-INT2.
However, this pin is not used by this library (and won't be in the next release neither).

Regards,
