### ISSUE TITLE
Does it work without the EVK board

### ISSUE THREAD

**Issue by Calypso514** [tdk-invn-oss/ultrasonic.arduino.ICUX0201#4]
Hello everyone,

I would like to mesure distances using the EV_MOD_ICU-10201-00 module but without the EVK board (I'm using a Firebeetle ESP32 board). Is that possible ?

Thanks for your help !

---
Notify: @tdk-invn-oss/ultrasonic-maintainers @tdk-invn-oss/arduino-maintainer

**Comment by rbuisson-invn** [comment]
Hello Calypso514,

Yes, you should be able to make it work by implementing a dedicated hardware.
Please note that a 1.8v power regulator will be required for VDD.
The ICU VDDIO supports 3.3v, so it complies with ESP32 IOs.

Regards,

**Comment by Calypso514** [comment]
Hello,

Thank you for your answer.
I implemented the specific Hardware as you said but when I call begin(), I get the error code 1. What does this error mean ?
