### ISSUE TITLE
What does LEDs Indicators in TOF EVK Board indicate?

### ISSUE THREAD

**Issue by vmanoj1996** [tdk-invn-oss/ultrasonic.arduino.ICUX0201#6]

**Comment by gferard-invn** [comment]
Hi Manoj,

using the Arduino library, the leds on EVK board aren't controlled by the library, the output aren't connected so their value might change in time.

**Comment by vmanoj1996** [comment]
Hi,
My interest was only in using the leds for debugging purposes. It would be great to understand what they mean.

**Comment by vmanoj1996** [comment]
For example in my  case,
D3, D5 are on
D6 is faint
Remaining LEDs are off. It would be nice to understand what they mean.

**Comment by rbuisson-invn** [comment]
Hello @vmanoj1996,

As stated above by @gferard-invn the LEDs on the TOF Eval board are left unconnected with the Arduino setup described in the README. For some reasons, they just randomly changed their state over the time :)
You can totally use them for debug, but only if you wire them to the Arduino board and control them in a meaningful manner.

Regard,
Remi

**Comment by vmanoj1996** [comment]
Understood now. Thank you
I thought I was doing something wrong that could make the LEDs sporadically respond.
