### ISSUE TITLE
Measurement stops after 1st sample in v1.0.2

### ISSUE THREAD

**Issue by vmanoj1996** [tdk-invn-oss/ultrasonic.arduino.ICUX0201#8]
I am facing this issue consistently on the version 1.0.2 of this driver.

### Reproduction steps (follow exactly):

1. Remove this library if installed from the Arduino library manager
7. Install v1.0.2
8. (Linux users) Goto /tmp/ and search for arduino. Delete them to clear any cache from previous compilation
9. Open ICUx0201_TargetDetection example and then upload it
10. **Once the upload is complete, unplug the board and reconnect**
11. Now it returns the range only once and stops working after that

Redo all the above steps with 1.0.1 and you would not see this issue.

### Connections:

 Use an Arduino MKR Zero board and connect the following:
1. INT1_0 to Pin 0
2. CSB_0 to Pin 1
3. MISO - 10
4. MOSI - 8
5. SCK - 9
Use either icu20201 or icu30201 for this test! The behavior is identical!

![2024-06-30 20 18 11](https://github.com/tdk-invn-oss/ultrasonic.arduino.ICUX0201/assets/8917581/bbbbed55-5a66-416c-9048-0a20c75b2bef)

**Comment by vmanoj1996** [comment]
This does not happen in 1.0.3. Am I hallucinating something or is it really a bug and is fixed in 1.0.3 ?

**Comment by rbuisson-invn** [comment]
Hello vmanoj,

The version 1.0.3 actually fixes an initialization issue, which explains the behavior you described with 1.0.2.
Now everything should be properly initialized.
Thanks for reporting!
